### ISSUE TITLE
Apply background

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/sparklaunch#19]
![image](https://user-images.githubusercontent.com/61826995/126033891-03d5c9fc-0a9c-4a67-a345-deee89e4ff0d.png)

Mock up:
![image](https://user-images.githubusercontent.com/61826995/126033903-c391a959-f9c7-4751-9224-3169031fc4cb.png)

**Comment by kojiadrianojr** [comment]
@mativanarquero naka ready na yung components for this papsahan nalng ng image
