### ISSUE TITLE
Fix number display

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/sparklaunch#78]
![image](https://user-images.githubusercontent.com/61826995/126990699-ece92962-9f66-4e75-8230-3aa214445cd3.png)

**Comment by mativanarquero** [comment]
Should we make the texts smaller din dito sir @swengr-janan?

**Comment by swengr-janan** [comment]
Bawasan lang decimal places. May fix na jan si @kojiadrianojr

**Comment by mativanarquero** [comment]
> Bawasan lang decimal places. May fix na jan si @kojiadrianojr

Noted po. Thank you.
